version: "3.4"

services:
  demo.api:
    image: ${DOCKER_REGISTRY-}demoapi
    build:
      context: .
      dockerfile: demo.api/Dockerfile

  postgresql:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: P@ssw0d!123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: demo-api-db # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./data/demo-api/pgsql:/var/lib/postgresql/data/
