version: "3.4"

services:
  demo.api:
    container_name: demo-api
    image: ${DOCKER_REGISTRY-}demoapi
    ports:
      - "8089:80"
    build:
      context: .
      dockerfile: demo.api/Dockerfile
    depends_on:
    - demo-db
   
  demo.api.bdd.tests:
    container_name: demo-bdd-test 
    image: ${DOCKER_REGISTRY-}demoapibddtests
    build:
      context: .
      dockerfile: demo.api.bdd.tests/Dockerfile
    volumes:
    - ./.testreports:/app/TestReport
    depends_on:
    - demo.api

  demo-db:
    container_name: demo-db
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: P@ssw0d!123
      POSTGRES_DB: demo-api-db
    volumes:
      - ./.data/demo-api/pgsql:/var/lib/postgresql/data/

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: vsarin@virtusa.com
  #     PGADMIN_DEFAULT_PASSWORD: P@ssw0rd

  demo-test-db:
    container_name: demo-test-db
    image: "postgres:latest"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: test-admin
      POSTGRES_PASSWORD: P@ssw0d!123
      POSTGRES_DB: demo-api-test-db


