apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo-app

build:
  local:
    useBuildkit: true
    useDockerCLI: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: demo-api
      custom:
        buildCommand: echo 'FROM busybox' | docker build --build-arg BUILD_CONFIG=Debug -f demo.api/Dockerfile .
deploy:
  helm:
    releases:
      - name: demo-app
        chartPath: ./k8s
        namespace: demo
        createNamespace: true
        # skipBuildDependencies: true
        artifactOverrides:
          image: demo-api
        imageStrategy:
          helm: {}
