{{- $DBHost := include "demo-api.database.host" . -}}
{{- $DBPort := include "demo-api.database.port" . -}}
{{- $DBName := include "demo-api.database.name" . -}}
{{- $DBUserName := include "demo-api.database.username" . -}}
{{- $DBPassword := include "demo-api.database.password" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-api.fullname" . }}-cfgmap
data:
  appsettings.k8s.json: |-
    {
        "Logging": {
            "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "Cache": {
            "Redis": {
            "Connection": "localhost:6379",
            "Ssl": false
            }
        },
        "apiConfig": {
            "basePath": "{{ .Values.apiPath }}",
            "pgsqlDBName": {{$DBName}},
            "pgsqlPort": {{$DBPort}},
            "pgsqlDatabase": {{$DBName}},
            "pgsqlUserId": {{$DBUserName}},
            "pgsqlPassword": {{$DBPassword}},
        }
    }