apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-api.fullname" . }}-cfgmap
data:
  appsettings.k8s.json: |-
    {
        "Logging": {
            "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "Cache": {
            "Redis": {
            "Connection": "localhost:6379",
            "Ssl": false
            }
        },
        "apiConfig": {
            "basePath": "{{ .Values.apiPath }}"
        }
    }