fullnameOverride: demoapi
replicaCount: 1
image:
  repository: registry.local:5000/demoapi
  tag: latest
  pullPolicy: Latest

service:
  type: ClusterIP
  port: 80

deployment:
  containerPort: 80

ingress:
  enabled: true
  annotations:
    - "nginx.ingress.kubernetes.io/rewrite-target=/"
    - "ingress.kubernetes.io/ssl-redirect: 'false'"
  path: /demo
