demo-api:
  image:
    repository: registry.local:5000/demo-api
    tag: "latest"
  apiPath: /api/demo/
  dbType: Postgres
  env:
    ASPNETCORE_ENVIRONMENT: Development
  ingress:
    enabled: true
    hosts:
      - host:
        paths:
          - path: /api/demo/
            pathType: ImplementationSpecific
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  postgresql:
    enabled: true
    auth:
      username: admin
      password: P@ssw0rd$123WER
      database: demo-app-db
    architecture: standalone
